version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./server:/app
      - /app/node_modules
    command: >
      /wait-for-it.sh db:5432 -- npm start
  db:
    image: postgres:12.11-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env.-db
    restart: on-failure
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf